public class Main {
    public static void main(String[] args) {
    Centro c = new Centro();
    Alumno Antonio_Luis =new Alumno("1º DAM","Antonio Luis");
    c.add_alumnos(Antonio_Luis);
    Alumno Sergio=new Alumno("1º DAM","Sergio");
    c.add_alumnos(Sergio);
    Alumno Nacho=new Alumno("1º DAM","Nacho");
    c.add_alumnos(Nacho);
    Alumno Adrian =new Alumno("1º DAM","Adrian");
    c.add_alumnos(Adrian);
    Alumno Javier =new Alumno("1º DAM","Javier");
    c.add_alumnos(Javier);
    Alumno Angel=new Alumno("1º DAM","Angel");
    c.add_alumnos(Angel);
    Alumno Pablo=new Alumno("1º DAM","Pablo");
    c.add_alumnos(Pablo);
    Alumno Alvaro_Conde=new Alumno("1º DAM","Alvaro Conde");
    c.add_alumnos(Alvaro_Conde);
    Alumno Manuel=new Alumno("1º DAM","Manuel");
    c.add_alumnos(Manuel);
    Alumno Natalia=new Alumno("1º DAM","Natalia");
    c.add_alumnos(Natalia);
     Alumno Alberto=  new Alumno("1º DAM","Alberto");
    c.add_alumnos(Alberto);
    Alumno Pablo_Gallego=new Alumno("1º DAM","Pablo Gallego");
    c.add_alumnos(Pablo_Gallego);
    Alumno pedro=new Alumno("1º DAM","pedro");
    c.add_alumnos(pedro);
    Alumno Pepe=new Alumno("1º DAM","Pepe");
    c.add_alumnos(Pepe);
    Alumno Alvaro=new Alumno("1º DAM","Alvaro");
    c.add_alumnos(Alvaro);
    Alumno ignacio=new Alumno("1º DAM","ignacio");
    c.add_alumnos(ignacio);
    c.add_alumnos(new Alumno("1º DAM","vacio 1"));
    c.add_alumnos(new Alumno("1º DAM","vacio 2"));
    c.add_alumnos(new Alumno("1º DAM","vacio 3"));
    c.add_alumnos(new Alumno("1º DAM","vacio 4"));
    c.add_alumnos(new Alumno("1º DAM","vacio 5"));
    c.add_alumnos(new Alumno("1º DAM","vacio 6"));
    Empresa Get_Join=new Empresa("Get Join", "ufhwuifgh");
    c.add_empresa(Get_Join);
    Empresa Smart_fenix=new Empresa("Smart fenix", "Córdoba");
    c.add_empresa(Smart_fenix);
    Empresa Caio_Ruiz =new Empresa("Caio Ruiz", "ufhwuifgh");
    c.add_empresa(Caio_Ruiz);
    Empresa D_Sastre =new Empresa("D-Sastre", "ufhwuifgh");
    c.add_empresa(D_Sastre);
    Empresa Movilcasa=new Empresa("Movilcasa", "ufhwuifgh");
    c.add_empresa(Movilcasa);
    Empresa IA_Automatizacion=new Empresa("IA Automatizacion", "ufhwuifgh");
    c.add_empresa(IA_Automatizacion);
    Empresa Punto_JS =new Empresa("Punto JS", "ufhwuifgh");
    c.add_empresa(Punto_JS);
    c.add_Practica(new Practica(Antonio_Luis,Get_Join,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Sergio,Smart_fenix,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Nacho,Caio_Ruiz,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Adrian,Caio_Ruiz,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Angel,D_Sastre,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Javier,Movilcasa,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Pablo,IA_Automatizacion,"INACTIVA","10/06/2026","6/04/2026"));
    c.add_Practica(new Practica(Alvaro_Conde,Punto_JS,"INACTIVA","10/06/2026","6/04/2026"));
    c.Listado();
    c.totalPracticasActivas();
    c.alumnosConPractica();
    c.ListadoP();
    c.ListadoC("Córdoba");
    c.alumnosSinPractica();
    }
}